exports.insertProfileImg = 'INSERT INTO ssi_user (kakao_user_number, profile_image_url) VALUES(?,?)'
exports.initUserTable = 'INSERT INTO ssi_user(kakao_user_number, nickname, profile_image_url, friend_count, post_count, song_count) VALUES(?, ?, ?, ?, ?, ?)'
exports.initUserHashTagTable = 'INSERT INTO ssi_user_hash_tag(ssi_user_kakao_user_number) VALUES(?)'
exports.selectUserProfile = 'SELECT a.nickname, a.profile_image_url, a.profile_music_uri, a.friend_count, a.post_count, a.song_count, b.tag1_cd, b.tag2_cd, b.tag3_cd, b.tag4_cd, b.tag5_cd FROM ssi_user AS a LEFT JOIN ssi_user_hash_tag AS b ON a.kakao_user_number = b.ssi_user_kakao_user_number WHERE a.kakao_user_number=?'
exports.editUserProfile = 'UPDATE ssi_user AS a LEFT JOIN ssi_user_hash_tag AS b ON a.kakao_user_number = b.ssi_user_kakao_user_number SET a.nickname=?, a.profile_image_url=?, a.profile_music_uri=?, b.tag1_cd=?, b.tag2_cd=?, b.tag3_cd=?, b.tag4_cd=?, b.tag5_cd=? WHERE a.kakao_user_number=?'
exports.updateUserLocation = 'UPDATE ssi_user SET location_depth1=?, location_depth2=?, location_depth3=? WHERE kakao_user_number=?'
exports.selectTotalPost = 'SELECT *, (SELECT IF (EXISTS (SELECT like_seq FROM ssi_post_like AS b WHERE b.liked_user_id =? AND a.post_seq = b.post_seq), 1, 0) AS likeNy) FROM ssi_post_list as a'
exports.updateCurrentMusic = 'UPDATE ssi_user SET current_music_uri=? WHERE kakao_user_number=?'
exports.selectOtherUserCurrentMusic = 'SELECT current_music_uri FROM ssi_user WHERE location_depth3=? AND NOT kakao_user_number =?'