exports.insertPostImgs = 'INSERT INTO ssi_post_images SET ?'
exports.initUserTable = 'INSERT INTO ssi_user SET ?'
exports.initUserHashTagTable = 'INSERT INTO ssi_user_hash_tag(kakao_user_number) VALUES(?)'
exports.selectUserProfile = 'SELECT * FROM ssi_user AS a LEFT JOIN ssi_user_hash_tag AS b ON a.kakao_user_number = b.kakao_user_number WHERE a.kakao_user_number=?'
exports.updateUserProfile = 'UPDATE ssi_user AS a LEFT JOIN ssi_user_hash_tag AS b ON a.kakao_user_number = b.kakao_user_number SET ? WHERE a.kakao_user_number =?'
exports.selectFavoriteSongList = 'SELECT * FROM ssi_user_song_list WHERE kakao_user_number =?'
exports.insertFavoriteSong = 'INSERT INTO ssi_user_song_list SET ?'
exports.updateUserLocation = 'UPDATE ssi_user SET region_code=? WHERE kakao_user_number=?'

exports.updateCurrentMusic = 'UPDATE ssi_user SET current_music_uri=? WHERE kakao_user_number=?'
exports.selectOtherUserCurrentMusic = 'SELECT current_music_uri FROM ssi_user WHERE location_depth3=? AND kakao_user_number NOT IN(?)'

exports.selectFriendList = 'SELECT (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.friend_kakao_user_number) as nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.friend_kakao_user_number) as profileImg, (SELECT profile_music_uri FROM ssi_user AS b WHERE b.kakao_user_number = a.friend_kakao_user_number) as profileMusicUri, friend_kakao_user_number FROM ssi_user_friend_list AS a WHERE kakao_user_number=?'
exports.isFriend = 'SELECT IF (EXISTS (SELECT user_friend_seq FROM ssi_user_friend_list WHERE kakao_user_number=? AND friend_kakao_user_number=?) , 1, 0) AS isFriend'

exports.selectTotalPost = 'SELECT *, (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.kakao_user_number) as nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.kakao_user_number) as profileImg, (SELECT IF (EXISTS (SELECT like_seq FROM ssi_post_like AS c WHERE c.kakao_user_number =? AND a.post_seq = c.post_seq), 1, 0)) AS likeNy, (SELECT count(*) FROM ssi_post_comment AS d WHERE a.post_seq = d.post_seq) as commentCount FROM ssi_post_list as a LEFT JOIN ssi_post_images AS e ON a.post_seq = e.post_seq WHERE a.del_ny = 0 ORDER BY a.post_seq DESC'
exports.selectLocationPost = 'SELECT *, (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.kakao_user_number) as nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.kakao_user_number) as profileImg, (SELECT IF (EXISTS (SELECT like_seq FROM ssi_post_like AS b WHERE b.kakao_user_number =? AND a.post_seq = b.post_seq), 1, 0)) AS likeNy, (SELECT count(*) FROM ssi_post_comment AS d WHERE a.post_seq = d.post_seq) as commentCount FROM ssi_post_list as a LEFT JOIN ssi_post_images AS e ON a.post_seq = e.post_seq WHERE del_ny = 0 AND region_depth1=? ORDER BY a.post_seq DESC'
exports.selectMyPost = 'SELECT *, (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.kakao_user_number) as nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.kakao_user_number) as profileImg, (SELECT IF (EXISTS (SELECT like_seq FROM ssi_post_like AS c WHERE c.kakao_user_number =? AND a.post_seq = c.post_seq), 1, 0)) AS likeNy, (SELECT count(*) FROM ssi_post_comment AS d WHERE a.post_seq = d.post_seq) as commentCount FROM ssi_post_list as a LEFT JOIN ssi_post_images AS e ON a.post_seq = e.post_seq WHERE a.del_ny = 0 AND kakao_user_number=? ORDER BY a.post_seq DESC'
exports.insertPost = 'INSERT INTO ssi_post_list SET ?'
exports.deletePost = 'UPDATE ssi_post_list SET del_ny = 1 WHERE post_seq=?'
// exports.updatePost = 'UPDATE ssi_post_list SET album_image_url=?, album_title=?, album_artist_name=?, input_text=?, mod_time=NOW() WHERE kakao_user_number=? AND post_seq=?'
exports.insertPostLikedUser = 'INSERT INTO ssi_post_like(post_seq, kakao_user_number) VALUES(?, ?)'
exports.deletePostLikedUser = 'DELETE FROM ssi_post_like WHERE post_seq =? AND kakao_user_number=?'
exports.selectPostLikedUserList = 'SELECT *, (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.kakao_user_number) AS nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.kakao_user_number) AS profileImg FROM ssi_post_like AS a WHERE post_seq =? ORDER BY like_seq ASC'
exports.selectPostComments ='SELECT *, (SELECT nickname FROM ssi_user AS b WHERE b.kakao_user_number = a.kakao_user_number) AS nickname, (SELECT profile_image FROM ssi_user AS b WHERE b.kakao_user_number =  a.kakao_user_number) AS profileImg FROM ssi_post_comment AS a WHERE a.post_seq =? AND a.del_ny = 0  ORDER BY comment_seq ASC'
exports.insertPostComments = 'INSERT INTO ssi_post_comment SET ?'
exports.increaseLikeCount = 'UPDATE ssi_post_list SET like_count = like_count+1 WHERE post_seq=?'
exports.decreaseLikeCount = 'UPDATE ssi_post_list SET like_count = like_count-1 WHERE post_seq=?'
